### ISSUE TITLE
Popup description when placing the cursor

### ISSUE THREAD

**Issue by concerob** [bkader/Skada-Revisited#38] opened 2021-02-21 19:43 UTC
When reviewing the damage / healing of two classes with equal branches for example 2 fury warriors, when clicking on the damage done the pop-up description shows the correct information but having two damage windows, and buying the damage of both, a detail occurs when place the mouse to see the pop-up box shows the information of the other player not the main one.
In this example it was a dungeon (I had found the detail with 2 heals shamans)
1. I have two skada windows.
2. On the left I place one and on the right the other
3. When hovering over to see the pop-up information, the pop-up information of the warrior on the right  appears in the warrior on the  left.

Note: I have the last update of the skada with cache and wtf files deleted

Left warrior
![image](https://user-images.githubusercontent.com/7861792/108636373-71c3ee80-744a-11eb-9550-1c389f4f3eb6.png)

Right warrior
![image](https://user-images.githubusercontent.com/7861792/108636403-a46de700-744a-11eb-8986-28eff29a7832.png)

**Comment by bkader** [comment] 2021-02-21 20:23
The screenshots aren't really readable and I didn't catch the full problem!

**Comment by concerob** [comment] 2021-02-21 20:26
Left warrior
![image](https://user-images.githubusercontent.com/7861792/108637531-adfa4d80-7450-11eb-866e-89d6ac11bd49.png)

Right warrior
![image](https://user-images.githubusercontent.com/7861792/108637553-cf5b3980-7450-11eb-8e0e-977f9a86fdd4.png)

**Comment by bkader** [comment] 2021-02-21 21:09
So you mean it's the same warrior, same fight and same mode but showing different numbers?

**Comment by concerob** [comment] 2021-02-21 22:05
When there are 2 characters with the same branch, the floating information only shows that of 1 character, but not the other.
In the example the warriors are
Bakusayga and the other is Shuhu, when comparing the damage done by them, the floating information on the Bakusayga detail shows Shushu's, but not Bakusayga's in the window where their damage detail is. In the window where the other warrior is if it shows its corresponding information

**Comment by bkader** [comment] 2021-02-21 22:09
I figured the problem and i tested it. I am looking for the issue as I am typing. I will let you know when it's fixed!
Thanks for reporting this.

**Comment by bkader** [comment] 2021-02-22 22:51
After checking the code since yesterday and trying to find the problem, it turned out it wasn't a problem but this is how the addon is. I tried for hours several solutions without altering the code but sadly to do so the whole code needs lots of changes.

When you are on a mode, for example `Damage`, you see the list of players. When you click on a player, the module stores the player's ID internally to itself `self.playerid = id` .. So now the module itself remembers the player. When you click on a spell, it does the same thing `self.spellname = label` ... Keep this in mind to understand what's said below.

When you have multiple windows, showing the same mode (_Damage, Damage taken, Healing ...etc_), the last clicked window is the one holding the data to show because as I said above it's stored per module, no per window.
So if you click on **Player A** on **Window 1**, you already told the module that you're checking that player.
If you click on **Player B** on **Window 2**, you change the player of the module.
Now if you click on a spell, the module has 2 data to look for : PlayerID and SpellID (or spell name) ... So no matter what you hover on the other windows, the module is looking for the what you clicked last, thus showing wrong tooltip if players have same spells, or showing absolutely nothing if the spells are different.

I hope I explained it in a easy way and unfortunately, this is a `wontfix` issue, so I am closing this issue.

_PS: I will keep searching and trying things, if I come up with a good method without modifying the code too much I will let you now._

**Comment by bkader** [comment] 2021-04-14 22:59
Skada used to store details about modes/players ..etc per module, this caused window tooltips to be misbehave.

**This is how to reproduce the issue**:
1. Have two windows showing the same set and the same mode.
2. Click on a player on one then a player on the other window.
3. Hover the spells and you will notice that the last clicked window shows proper tooltips while the other doesn't show unless the player is of the same class or they have common spells (i.e : Auto Attack).
4. Right-click on the window that doesn't work and it will swap to what's the active window is showing.

This is not a bug but rather how Skada works, at least so far.

**What's on the next update?**
The next update will allow players to freely have multiple windows showing the same set/mode and the tooltips will show the appropriate info because data is stored/cache per window instead of being stored per module.

**How is this useful?**
Player tend most of times to compare their characters to the same classes in the raid, and because Skada is not Details, the comparison window doesn't and won't be built-in **BUT**, if you want to compare, here is an example of how I do it:

1. Have you regular windows for UI purposes just like you are used to do (_damage, healing, threat ... etc_).
2. Create as many comparison windows as you want, have them stacked to each other and of course hidden.
3. The feature **child-parent** that was built-in but disabled will, after the update, be available and will allow you to attach a window to a parent (_one-to-one relation_). Whatever you do and wherever you navigate on the parent, the child will follow.
4. Let's assume I have three hidden windows: **Window A** parent of **Window B** which is a parent of **Window C**. The three windows are snapped to each other and hidden, only shown when I click Skada minimap button.
5. If I want to compare, after clicking the minimap button, I select the set/mode I want on **Window A**, which causes **Window B** to follow, which by consequence causes **Window C** to follow.
6. I select a player on **Window A**, both windows **B** & **C** will follow as well, but that's not a problem.
7. I right-click **Window B** to select a different player, **Window C** will follow but again, it's not a problem.
8. I right-click on **Window C** to select a 3rd player (_preferably if the same class_) and here I have 3 windows showing 3 players of the same class and their spells.
9. Now, any spell I click on **Window A** will cause the other windows to follow and show that spell info for the other 2 players.

If it is complicated to understand, You can always ask me on Discord to explain it more.

**Closed by bkader** 2021-04-14 22:59 UTC
Labels: enhancement
